### PR TITLE
GitManager is invoked during artefact save. Resolves #6. Fixing empty…

### LINKED ISSUE #6: Git ignore management
Saving an artefact with alpheus adds the artefact to the gitignore

### PR DESCRIPTION
**Pull request by dgrechka**
* Adds .gitignore records management (saved artefacts are added to .gitignore)
* fixing save of empty directory artefact (tests added)

### CODE REVIEW

File: AlpheusCore/API.fs [hunk 1]
```diff
@@ -196,6 +196,12 @@ let saveAsync (experimentRoot, artefactId) storageName saveAll =
             let save = StorageFactory.getStorageSaver experimentRoot storageToSaveTo
             let saveDescriptors = artefactsToSave |> Array.map (fun art -> (idToFullPath experimentRoot artefactId),art.ActualHash.Value)
             let! _ = save saveDescriptors
+
+            // adding the saved artefact into the gitignore
+            let newIgnoreEntries = artefactsToSave |> Array.map (fun art -> art.Id.ToString())
```
Comment (dvoits) [inline AlpheusCore/API.fs]: `ArtefactId.ToString()` potentially can be an arbitrary string. I suggest using the following:

```FSharp
open PathUtils
let newIgnoreEntry art = art.Id |> idToExperimentPath |> unixPath
```

**Review by dvoits — CHANGES_REQUESTED** [review]
Please see the comment in the API.fs

File: AlpheusCore/API.fs (hunk 1 above)
Comment (dgrechka) [reply AlpheusCore/API.fs]: Agree
